apiVersion: perf.kubestone.xridge.io/v1alpha1
kind: Fio
metadata:
  name: fio-sample
spec:
  volume:
    volumeSource:
      emptyDir: {}
      persistentVolumeClaim: null    # Needs to be removed from the base
    persistentVolumeClaimSpec: null  # Needs to be removed from the base
