---
apiVersion: perf.kubestone.xridge.io/v1alpha1
kind: Iperf3
metadata:
  name: iperf3-sample
spec:
  image:
    name: xridge/iperf3:3.7.0
    pullPolicy: IfNotPresent
    # pullSecret: docker-pull-secret

  serverConfiguration:
    cmdLineArgs: --verbose
    # nodeSelector: null
    affinity:
      # nodeAffinity: null
      # podAffinity: null
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - store
          topologyKey: "kubernetes.io/hostname"

  UDP: false
